language: python

matrix:
  include:
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial

cache: pip3

before_install:
- npm install npm@latest -g

install:
- pip3 install tox-travis
- pip3 install bumpversion
- npm install @semantic-release/exec
- npm install @semantic-release/git

script:
- tox

before_deploy:
- sudo apt-get update
- pip3 install -r requirements.txt
- pip3 install -r requirements-dev.txt
- pip3 install pypandoc
- sudo apt-get install pandoc
- pip3 install --editable .

deploy:
  - provider: script
    script: npx semantic-release
    skip_cleanup: true
    on:
      python: '3.5'
      branch: master
  - provider: pypi
    user: watson-devex
    password: $PYPI_PASSWORD
    repository: https://upload.pypi.org/legacy
    skip_cleanup: true
    on:
      python: '3.5'
      tags: true
